version: '2.1'

volumes:
  postgres_data_dev: {}

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=concepttoclinic

  interface:
    build:
      context: .
      dockerfile: ./compose/interface/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - prediction
    environment:
      - POSTGRES_USER=concepttoclinic
      - USE_DOCKER=yes
      - SECRET_KEY=notverysecret
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DATABASE_URL=postgres://concepttoclinic:postgres@postgres:5432/concepttoclinic
    volumes:
      - ./interface/:/app
      - ./tests/assets/test_image_data/small:/images
      - ./.git/logs/HEAD:/HEAD
    ports:
      - "8000:8000"

  prediction:
    build:
      context: .
      dockerfile: ./compose/prediction/Dockerfile-dev
    command: flask run --host=0.0.0.0 --port=8001
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=src/factory.py
    volumes:
      - ./prediction/:/app
      - ./tests/assets/test_image_data/small:/images
    ports:
      - "8001:8001"


